- app/javascript/mastodon/emoji.js
繰り返し処理の記述が多かった為それらをまとめるためのリファクタです。生成テキストの変化はありません。
> emojify_knzk()リファクタ

- app/javascript/styles/components.scss
> 絵文字をlargeで拡大表示できるようにする

- app/javascript/mastodon/features/compose/components/announcements.js
> BBCode一覧追記

- app/javascript/mastodon/actions/timelines.js
- app/javascript/mastodon/components/status.js
- app/javascript/mastodon/components/status_list.js
- app/javascript/mastodon/features/account_timeline/index.js
- app/javascript/mastodon/locales/ja.json
- app/javascript/mastodon/reducers/timelines.js
- app/javascript/styles/components.scss
by [kazu0617](https://github.com/kazu0617)さん
> /web/accounts/でピン留めトゥートを表示させる

- app/javascript/mastodon/features/enquete/components/enquete_inputs.js
- app/lib/enquete_extension.rb
> アンケート機能で1日を12時間として扱っていたバグを修正

- app/javascript/styles/enquete.scss
> knzk-gauge-icon.pngが表示されない問題を修正

- app/javascript/mastodon/is_mobile.js
- app/javascript/styles/components.scss
- app/javascript/styles/rtl.scss
もし前の状態に戻すので大丈夫であればこれをマージしてください
> モバイルレイアウト(?)になる画面サイズを戻す

- app/javascript/styles/components.scss
- app/lib/formatter.rb
[![https://yuzu.gyazo.com/ede63e5c858b4d4cf3b3862441799922](https://t.gyazo.com/teams/yuzu/ede63e5c858b4d4cf3b3862441799922.gif)](https://yuzu.gyazo.com/ede63e5c858b4d4cf3b3862441799922)
> 点滅が使用できない問題を修正

- app/javascript/mastodon/features/emoji/emoji.js
参照: https://github.com/dwango/mastodon/blob/friends.nico/app/javascript/mastodon/features/emoji/emoji.js#L11
> :nicoru:回転に負の角度を使えるようにする

- Gemfile
- app/javascript/styles/dark/basics.scss
- app/javascript/styles/dark/components.scss
- app/javascript/styles/electronic/basics.scss
- app/javascript/styles/electronic/components.scss
- app/javascript/styles/mastodon/basics.scss
- app/javascript/styles/mastodon/components.scss
- app/lib/formatter.rb
改行関係でまだ問題があるようなので修正できる人いればお願いします。
> Markdown対応

- app/javascript/styles/bbcode.scss
> codeとquoteのcssを変更

- app/lib/formatter.rb
> カスタム絵文字が表示できない問題を修正

- app/javascript/mastodon/actions/onboarding.js
- app/javascript/mastodon/actions/tutorial.js
- app/javascript/mastodon/components/status_action_bar.js
- app/javascript/mastodon/containers/status_container.js
- app/javascript/mastodon/features/tutorial/components/tutorial.js
- app/javascript/mastodon/features/tutorial/components/tutorial_contents.js
- app/javascript/mastodon/features/tutorial/components/tutorial_nav.js
- app/javascript/mastodon/features/tutorial/containers/tutorial_container.js
- app/javascript/mastodon/features/tutorial/utils/get_target_position.js
- app/javascript/mastodon/features/tutorial/utils/scroll.js
- app/javascript/mastodon/features/ui/components/columns_area.js
- app/javascript/mastodon/features/ui/containers/columns_area_container.js
- app/javascript/mastodon/features/ui/index.js
- app/javascript/mastodon/reducers/index.js
- app/javascript/mastodon/reducers/settings.js
- app/javascript/mastodon/reducers/tutorial.js
- app/javascript/styles/mastodon.scss
- app/javascript/styles/mastodon/tutorial.scss
Plese check PR(#72) before see this pull .
Import friends.nico custom tutorial(dwango/mastodon#135)
> Custom Tutorial

- app/javascript/mastodon/reducers/settings.js
> Revert "Change default columns order"

- app/models/media_attachment.rb
- app/serializers/initial_state_serializer.rb
- config/application.rb
- lib/paperclip/audio_transcoder.rb
> Audio uploads feature

- .env.production.sample
- app/javascript/mastodon/features/compose/components/compose_form.js
- app/serializers/initial_state_serializer.rb
- app/validators/status_length_validator.rb
文字数上限をenvファイルから自由に変更できるようにします。
> Make character limit configurable

- app/javascript/mastodon/actions/compose.js
- app/javascript/mastodon/components/icon_button.js
- app/javascript/mastodon/features/compose/components/compose_form.js
- app/javascript/mastodon/features/compose/components/doodle_button.js
- app/javascript/mastodon/features/compose/components/doodle_modal.js
- app/javascript/mastodon/features/compose/containers/doodle_button_container.js
- app/javascript/mastodon/features/ui/components/doodle_modal.js
- app/javascript/mastodon/features/ui/components/modal_root.js
- app/javascript/mastodon/reducers/compose.js
- app/javascript/styles/application.scss
- app/javascript/styles/mastodon/components.scss
- app/javascript/styles/mastodon/doodle.scss
- package.json
- yarn.lock
> Doodle feature

- app/javascript/mastodon/components/autosuggest_textarea.js
- app/javascript/mastodon/reducers/compose.js
> Use zerowidth spaces for emojis

- app/controllers/settings/keyword_mutes_controller.rb
- app/helpers/settings/keyword_mutes_helper.rb
- app/lib/feed_manager.rb
- app/models/glitch.rb
- app/models/glitch/keyword_mute.rb
- app/views/settings/keyword_mutes/_fields.html.haml
- app/views/settings/keyword_mutes/_keyword_mute.html.haml
- app/views/settings/keyword_mutes/edit.html.haml
- app/views/settings/keyword_mutes/index.html.haml
- app/views/settings/keyword_mutes/new.html.haml
- config/locales/en.yml
- config/locales/ja.yml
- config/navigation.rb
- config/routes.rb
- db/migrate/20170716191202_add_hide_notifications_to_mute.rb
- db/migrate/20170914032032_default_existing_mutes_to_hiding_notifications.rb
- db/migrate/20171009222537_create_keyword_mutes.rb
- db/migrate/20171021191900_move_keyword_mutes_into_glitch_namespace.rb
- db/migrate/20171028221157_add_reblogs_to_follows.rb
- db/schema.rb
- spec/controllers/settings/keyword_mutes_controller_spec.rb
- spec/fabricators/glitch_keyword_mute_fabricator.rb
- spec/helpers/settings/keyword_mutes_helper_spec.rb
- spec/lib/feed_manager_spec.rb
- spec/models/glitch/keyword_mute_spec.rb
> Keyword muting

- app/javascript/mastodon/features/compose/components/compose_form.js
- app/javascript/mastodon/features/compose/components/upload_button.js
- app/javascript/styles/mastodon/components.scss
> Full-width tootbox panel to make room for buttons

- app/javascript/mastodon/features/account/components/action_bar.js
- app/javascript/mastodon/locales/defaultMessages.json
- app/javascript/mastodon/locales/en.json
- app/javascript/mastodon/locales/ja.json
- app/javascript/styles/dark/components.scss
- app/javascript/styles/electronic/components.scss
- app/javascript/styles/mastodon/components.scss
※リモートのアカウントは正確な日時が表示できないので無効化しています
> プロフィール欄に登録日の表示を追加
